### PR TITLE
Translate into visibility effect, Issue #9

### PR DESCRIPTION
**Pull request by Karanagarwal12**
Animated the trade and world sections as described in the issue #9.

### CODE REVIEW

**Comment by mohammedasimahmed** [comment]
the translate effect comes into action when the last section starts to comes into view not when the trade and world section start to come into view

**Comment by Karanagarwal12** [comment]
Done, fixed the problem. Now it is working as needed.
Thanks

**Comment by mohammedasimahmed** [comment]
the translate effect for world section also occurs when only trade section is in view check this ,  you can make another isMidInView for world section and apply the translate effect when that comes into view

**Comment by Karanagarwal12** [comment]
@mohammedasimahmed, Done, added different refs for trade and world sections. Now they are appearing when they are in view saperately.
Thanks

**Comment by mohammedasimahmed** [comment]
pr accepted

**Pull request closed without merging**
